window.CarraProfile = (() => {
  const defaults = { name: 'Alex Morgan', vehicle: '2022 Kia EV6', mileage: 36120, insurance: 'Carra Auto', warranty: 'Carra Care' };
  let memory = { ...defaults };
  const valid = value => value && ['name','vehicle','insurance','warranty'].every(k => typeof value[k] === 'string' && value[k].length <= 100) && Number.isInteger(value.mileage) && value.mileage >= 0 && value.mileage <= 2000000;
  function get() { try { const saved = JSON.parse(localStorage.getItem('carra.profile.v1')); if (valid(saved)) memory = saved; } catch {} return { ...memory }; }
  function save(value) { if (!valid(value)) throw new Error('Check your profile details.'); memory = { ...value }; try { localStorage.setItem('carra.profile.v1', JSON.stringify(value)); return true; } catch { return false; } }
  return { get, save };
})();

window.CarraMyPage = (() => {
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  let active = 0;
  let preview;
  let objectUrl;
  function dispose() { active++; preview?.close(); preview?.remove(); preview = null; if (objectUrl) URL.revokeObjectURL(objectUrl); objectUrl = null; }
  function db() { return new Promise((resolve,reject) => { const r = indexedDB.open('carra-document-library',1); r.onupgradeneeded=()=>r.result.createObjectStore('documents',{keyPath:'id'}); r.onsuccess=()=>resolve(r.result); r.onerror=()=>reject(r.error); }); }
  async function stored(action, value) { const database=await db(); try { return await new Promise((resolve,reject)=>{ const tx=database.transaction('documents',action === 'list' ? 'readonly' : 'readwrite'); const store=tx.objectStore('documents'); const r=action==='list'?store.getAll():action==='put'?store.put(value):store.delete(value); tx.oncomplete=()=>resolve(r.result); tx.onerror=()=>reject(tx.error); tx.onabort=()=>reject(tx.error); }); } finally { database.close(); } }
  function createPreview(title) {
    preview?.remove(); if(objectUrl) URL.revokeObjectURL(objectUrl); objectUrl=null;
    preview=document.createElement('dialog'); preview.className='library-preview';
    preview.innerHTML=`<div class="library-preview-head"><h2>${esc(title)}</h2><button type="button" class="btn btn-secondary">Close</button></div><div class="library-preview-body"></div>`;
    document.body.appendChild(preview); preview.querySelector('button').onclick=()=>preview.close();
    preview.addEventListener('close',()=>{ if(objectUrl) URL.revokeObjectURL(objectUrl); objectUrl=null; });
    preview.showModal(); return preview.querySelector('.library-preview-body');
  }
  function onboarding(host) {
    let step=0, value=CarraProfile.get();
    const render=()=>{
      host.innerHTML=`<div class="profile-setup"><a href="#/my" class="setup-back">← My page</a><p class="eyebrow">A home for your car</p><h1>${step===0?'Let’s start with your car.':'Bring your protection together.'}</h1><p>${step===0?'A few details help keep the right information in view.':'Choose the plans for your presentation profile. You can keep the policy files in your library.'}</p><ol class="setup-steps"><li ${step===0?'aria-current="step"':''}>1 · Your car</li><li ${step===1?'aria-current="step"':''}>2 · Your protection</li></ol><form id="profile-form">${step===0?`<label>Your name<input name="name" value="${esc(value.name)}" maxlength="100" required autocomplete="given-name"></label><label>Vehicle<input name="vehicle" value="${esc(value.vehicle)}" maxlength="100" required placeholder="2022 Kia EV6"></label><label>Mileage<input name="mileage" value="${value.mileage}" type="number" min="0" max="2000000" step="1" required></label>`:`<label>Auto insurance<select name="insurance"><option value="Carra Auto" ${value.insurance?'selected':''}>Carra Auto · Comprehensive & collision</option><option value="" ${!value.insurance?'selected':''}>Add insurance later</option></select></label><label>Vehicle warranty<select name="warranty"><option value="Carra Care" ${value.warranty?'selected':''}>Carra Care · Vehicle protection</option><option value="" ${!value.warranty?'selected':''}>Add warranty later</option></select></label><div class="setup-plan-note"><strong>Your protection, organized.</strong><p>Review coverage details on My page and attach your policy documents to the library.</p></div>`}<div class="setup-actions">${step?'<button type="button" class="btn btn-secondary" id="setup-prev">Back</button>':''}<button class="btn btn-primary" type="submit">${step?'Save my profile':'Continue'}</button></div><p class="setup-save-status" role="status"></p></form><small class="profile-footnote">Illustrative profile for the hackathon. Plans are not connected to an insurer or manufacturer.</small></div>`;
      host.querySelector('#setup-prev')?.addEventListener('click',()=>{const form=new FormData(host.querySelector('form'));value.insurance=form.get('insurance');value.warranty=form.get('warranty');step=0;render();});
      host.querySelector('form').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target);if(step===0){value={...value,name:form.get('name').trim(),vehicle:form.get('vehicle').trim(),mileage:Number(form.get('mileage'))};if(!value.name||!value.vehicle)return;step=1;render();host.querySelector('h1').setAttribute('tabindex','-1');host.querySelector('h1').focus();}else{value={...value,insurance:form.get('insurance'),warranty:form.get('warranty')};const persisted=CarraProfile.save(value);if(!persisted)showToast('Profile saved for this session. Browser storage is unavailable.');location.hash='/my';}};
    };render();
  }
  async function mount(host,{drafts=[],showOriginal}={}) {
    const version=++active, p=CarraProfile.get();
    const covered=p.warranty && p.mileage<60000;
    host.innerHTML=`<div class="my-page"><header class="my-heading"><div><p class="eyebrow">Your car. Your peace of mind.</p><h1>${esc(p.name.split(' ')[0])}’s garage</h1><p>Your protection and paperwork, all in one place.</p></div><a href="#/onboarding" class="btn btn-secondary">Edit profile</a></header>
    <section class="garage-hero"><div class="garage-vehicle"><span class="garage-icon" aria-hidden="true"><svg viewBox="0 0 100 56"><path d="M13 31 23 12h51l13 19M8 31h84v17H8zM19 48v6m62-6v6M18 37h13m38 0h13" fill="none" stroke="currentColor" stroke-width="4" stroke-linejoin="round"/></svg></span><div><span class="garage-overline">Your vehicle</span><h2>${esc(p.vehicle)}</h2><p>${p.mileage.toLocaleString('en-US')} miles <span>·</span> Personal vehicle</p></div></div><div class="garage-hero-action"><span>Your next visit, a little clearer.</span><a href="#/analyze/new" class="btn btn-primary">Review an estimate →</a></div></section>
    <div class="garage-protection"><section class="plan-card insurance-card"><div class="plan-heading"><span class="plan-symbol" aria-hidden="true">I</span><span class="plan-status">${p.insurance?'On file':'Add a plan'}</span></div><p class="eyebrow">Auto insurance</p><h2>${esc(p.insurance||'Keep your policy here')}</h2><p>${p.insurance?'Comprehensive & collision':'Organize your provider and policy documents.'}</p>${p.insurance?'<div class="plan-metrics"><div><strong>$500</strong><span>Collision deductible</span></div><div><strong>Sep 2027</strong><span>Renewal</span></div></div><details><summary>View policy details</summary><dl><dt>Policy</dt><dd>CA-2048-0622</dd><dt>Comprehensive deductible</dt><dd>$250</dd><dt>Roadside assistance</dt><dd>Up to $100 per approved event</dd><dt>Rental benefit</dt><dd>Up to $40/day for 5 days on a covered claim</dd></dl><p>Contact the provider before arranging a claim repair. Benefits depend on the covered event.</p></details>':'<a href="#/onboarding">Add insurance →</a>'}</section>
    <section class="plan-card warranty-card"><div class="plan-heading"><span class="plan-symbol" aria-hidden="true">W</span><span class="plan-status">${covered?'Protection on file':p.warranty?'Mileage limit reached':'Add a plan'}</span></div><p class="eyebrow">Vehicle warranty</p><h2>${esc(p.warranty||'Know your protection')}</h2><p>${p.warranty?'Component protection for your next chapter.':'Bring your warranty details into one place.'}</p>${p.warranty?`<div class="plan-metrics"><div><strong>${Math.max(0,60000-p.mileage).toLocaleString('en-US')} mi</strong><span>Until the mileage limit</span></div><div><strong>$0</strong><span>Covered-repair deductible</span></div></div><details><summary>View warranty details</summary><dl><dt>Plan</dt><dd>CC-2022-4816</dd><dt>Ends</dt><dd>Sep 19, 2027 or 60,000 miles, whichever comes first</dd><dt>Components</dt><dd>Electrical, drive unit, high-voltage battery, charge port, cooling pump, and ignition coils</dd><dt>Excluded</dt><dd>Routine maintenance, wear items, and 12V battery replacement</dd></dl><p>Confirm the diagnosis and obtain repair authorization with the plan administrator.</p></details>`:'<a href="#/onboarding">Add warranty →</a>'}</section></div>
    <section class="document-vault" aria-labelledby="vault-title"><div class="vault-heading"><div><p class="eyebrow">Less searching. More knowing.</p><h2 id="vault-title">Your documents</h2></div><button class="btn btn-primary" type="button" id="library-add">+ Add document</button></div><div class="library-upload" hidden><label>Save as<select id="library-type"><option>Receipt</option><option>Estimate</option><option>Insurance</option><option>Warranty</option><option>Service record</option></select></label><label>Choose PDF or photo<input id="library-file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"></label><p>Saved in this browser · Up to 10 MB · No document is sent externally</p></div><div class="vault-controls"><label><span class="visually-hidden">Search documents</span><input type="search" id="library-search" placeholder="Search vehicle, shop, or document"></label><label><span class="visually-hidden">Document type</span><select id="library-filter"><option value="all">All documents</option><option>Estimate</option><option>Receipt</option><option>Service record</option><option>Insurance</option><option>Warranty</option></select></label></div><p id="library-message" role="status">Loading your library…</p><div class="library-list"></div></section><footer class="profile-footnote">Illustrative profile for the hackathon. Sample policies and source documents are included; your added files stay in this browser.</footer></div>`;
    let rows=drafts.map(d=>({id:d.id,title:d.vehicle,detail:d.shop,type:d.documentKind==='service_record'?'Service record':'Estimate',date:d.date,amount:d.total,source:d.sourcePdf,draft:d,report:`#/analyze/${d.id}${d.completed?'':'/review'}`}));
    const list=host.querySelector('.library-list'), message=host.querySelector('#library-message');
    const render=()=>{if(version!==active)return;const search=host.querySelector('#library-search').value.toLowerCase();const filter=host.querySelector('#library-filter').value;const selected=rows.filter(r=>(filter==='all'||r.type===filter)&&`${r.title} ${r.detail} ${r.type}`.toLowerCase().includes(search));list.innerHTML=selected.length?selected.map(r=>`<article class="library-row"><span class="library-file-icon" aria-hidden="true">${r.file?.type.startsWith('image/')?'IMG':'PDF'}</span><div class="library-description"><span class="library-type">${esc(r.type)}</span><h3>${esc(r.title)}</h3><p>${esc(r.detail)} · ${esc(r.date||'Date not stated')}</p></div><div class="library-row-actions">${r.amount!=null?`<strong>${CarraCore.money(r.amount)}</strong>`:''}<button type="button" class="btn btn-quiet" data-library-open="${esc(r.id)}">Open</button>${r.report?`<a href="${r.report}" class="library-report-link">${r.draft.completed?'Report':'Review'}</a>`:''}${r.local?`<button type="button" class="library-remove" data-library-remove="${esc(r.id)}" aria-label="Remove ${esc(r.title)}">Remove</button>`:''}</div></article>`).join(''):'<div class="library-empty"><h3>No documents here yet.</h3><p>Add a file or try another search.</p></div>';};
    host.querySelector('#library-search').oninput=render;host.querySelector('#library-filter').onchange=render;
    host.querySelector('#library-add').onclick=()=>{const panel=host.querySelector('.library-upload');panel.hidden=!panel.hidden;if(!panel.hidden)host.querySelector('#library-type').focus();};
    const results=await Promise.allSettled([stored('list'),fetch('/api/samples').then(r=>{if(!r.ok)throw Error();return r.json();})]);
    if(version!==active)return;
    if(results[0].status==='fulfilled')rows.push(...results[0].value.map(r=>({...r,local:true})));
    if(results[1].status==='fulfilled')for(const [id,type,title] of [['estimate-29','Estimate','Battery & charging estimate'],['service_record-29','Service record','Battery service record'],['estimate-24','Receipt','Service receipt']]){const sample=results[1].value.samples.find(s=>s.id===id);if(sample)rows.push({id:`sample-${id}`,title,detail:sample.vehicle+' · '+sample.shop,type,date:sample.date,amount:sample.total,source:sample.url});}
    message.textContent=results.some(r=>r.status==='rejected')?'Some documents could not load. Your available files are shown below.':`${rows.length} documents in one place`;render();
    host.querySelector('#library-file').onchange=async event=>{
      const file=event.target.files[0];if(!file)return;
      if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){message.textContent='Choose a PDF, JPEG, PNG, or WebP up to 10 MB.';return;}
      const row={id:crypto.randomUUID(),title:file.name,detail:p.vehicle,type:host.querySelector('#library-type').value,date:new Date().toISOString().slice(0,10),file,local:true};
      try{await stored('put',row);if(version!==active)return;rows.unshift(row);message.textContent='Document saved to your library.';event.target.value='';render();}catch{if(version===active)message.textContent='The file could not be saved. Check browser storage and try again.';}
    };
    list.onclick=async event=>{const button=event.target.closest('button');if(!button)return;const id=button.dataset.libraryOpen||button.dataset.libraryRemove;const row=rows.find(r=>r.id===id);if(!row)return;
      if(button.dataset.libraryRemove){try{await stored('delete',id);if(version!==active)return;rows=rows.filter(r=>r.id!==id);render();message.textContent='Document removed from this library.';}catch{message.textContent='Could not remove the document. Try again.';}return;}
      const target=createPreview(row.title);
      if(row.file?.type.startsWith('image/')){objectUrl=URL.createObjectURL(row.file);target.innerHTML=`<img class="library-original-image" src="${objectUrl}" alt="${esc(row.title)}">`;}
      else if(row.file||row.source)CarraDocuments.pdfViewer(target,row.file||row.source);
      else if(row.draft&&showOriginal)showOriginal(row.draft,target);
      else target.textContent='The original file is not available in this browser.';
    };
  }
  return {mount,onboarding,dispose};
})();
