import { narratives } from './dataset-narratives.js';
const done = new Set(['completed','performed','warranty_completed','courtesy_check','completed_after_additional_authorization']);
const short = value => { const words=value.split(/\s+/); return words.slice(0,7).join(' ')+(words.length>7?'…':''); };
export function summarizeReport(d, {money,reconciliation,sources,quotes}) {
  const service=d.documentKind==='service_record';
  const invoice=!service && d.documentType==='invoice';
  const sourceLabel=service?'From your service record':invoice?'From your invoice':'From your estimate';
  const sourceItems=d.sourceData?.items||d.sourceData?.work_performed;
  const matches=d.origin==='dataset' && Array.isArray(sourceItems) && sourceItems.length===d.items.length && d.total===d.sourceData.totals?.total && d.tax===d.sourceData.totals?.tax && d.concern===(d.sourceData.customer_concern||'') && d.items.every((item,i)=>item.title===sourceItems[i].normalized_title && item.source_text===sourceItems[i].source_text && item.status===sourceItems[i].status && item.total===sourceItems[i].line_total);
  const narrative=matches?narratives[d.sampleId.split('-').at(-1)]:null;
  const rows=d.items.map((item,i)=>({...item,i}));
  const approved=rows.filter(i=>['authorized','approved'].includes(i.status));
  const proposed=rows.filter(i=>i.status==='recommended');
  const completed=rows.filter(i=>done.has(i.status));
  const pending=rows.filter(i=>i.status==='pending_diagnosis');
  const extra=rows.filter(i=>i.status==='additional_authorization_required');
  const declined=rows.filter(i=>i.status==='declined');
  const context=rows.map(i=>`Line ${i.i+1}: ${i.title}. Status: ${i.status}. Listed amount: ${money(i.total)}.`);
  const totalText=`Listed total: ${money(d.total)}. Fees: ${money(d.fees)}. Tax: ${money(d.tax)}.`;
  context.push(totalText);
  const notes=matches && typeof d.sourceData.notes==='string' && !/simulated|OCR testing|compact receipt uses|parts and labor shown|two-page|completed and declined items/i.test(d.sourceData.notes) ? d.sourceData.notes : null;
  if(notes)context.push(`Shop note: ${notes}`);
  const originalTotals=matches && d.total===d.sourceData.totals?.total ? d.sourceData.totals:null;
  const payment=originalTotals && typeof originalTotals.deposit==='number' && typeof originalTotals.balance_due==='number' ? `Deposit recorded: ${money(originalTotals.deposit)}. Balance due: ${money(originalTotals.balance_due)}.`:null;
  if(payment)context.push(payment);
  const limit=matches?d.sourceData.authorization_limit:null;
  if(typeof limit==='number')context.push(`Authorization limit: ${money(limit)}.`);
  sources.S1={id:'S1',tier:'your_estimate',publisher:service?'Your service record':invoice?'Your invoice':'Your document',title:`${d.shop}, reviewed details`,originalText:context.join('\n')};
  const addQuote=(id,text,locator)=>{quotes[id]={id,sourceId:'S1',locator,text:text.match(/^(?:\S+\s*){1,40}/)?.[0].trim()||text};return id;};
  rows.forEach(i=>addQuote(`D${i.i+1}`,context[i.i],`Line ${i.i+1} details`));
  addQuote('DT',totalText,'Totals');
  if(notes)addQuote('DN',`Shop note: ${notes}`,'Shop note');
  if(payment)addQuote('DP',payment,'Payment details');
  if(typeof limit==='number')addQuote('DL',`Authorization limit: ${money(limit)}.`,'Authorization');
  const refs=list=>list.map(i=>`D${i.i+1}`);
  const names=list=>list.slice(0,2).map(i=>short(i.title)).join(' + ')+(list.length>2?` + ${list.length-2} more`:'');
  const sum=list=>list.every(i=>i.total!=null)?money(list.reduce((n,i)=>n+i.total,0)):null;
  const candidates=[];
  const add=(text,quoteIds,priority=0)=>candidates.push({text,quoteIds,priority,provenance:sourceLabel});
  if(reconciliation.incomplete)add('Some amounts are missing. Confirm the total before treating this as a complete bill.',['DT'],100);
  else if(reconciliation.needsReview)add(`The listed total differs from lines plus fees and tax by ${money(reconciliation.difference)}.`,['DT',...refs(rows)],100);
  if(extra.length)add(`Not yet approved: ${names(extra)}${sum(extra)?` (${sum(extra)})`:''}.`,refs(extra),95);
  if(declined.length)add(`Declined, not completed: ${names(declined)}.`,refs(declined),94);
  if(pending.length)add(`Still conditional: ${names(pending)}${sum(pending)?` (${sum(pending)})`:''}.`,refs(pending),93);
  if(payment)add(`${money(originalTotals.deposit)} deposit recorded; ${money(originalTotals.balance_due)} remains due, rather than the full invoice total.`,['DP'],98);
  if(typeof limit==='number')add(`Authorization is capped at ${money(limit)}; confirm any additional work before it begins.`,['DL'],97);
  const redundantNote=notes && (payment && /deposit|balance/i.test(notes) || typeof limit==='number' && /authorization/i.test(notes) || extra.length && /authoriz/i.test(notes) || pending.length && /provisional|not authorized until|subject to test/i.test(notes) || declined.length && /approved and declined/i.test(notes));
  if(notes && !redundantNote)add(`Shop note: ${notes}`,['DN'],80);
  if(approved.length && (proposed.length||extra.length||pending.length))add(`Approved scope: ${names(approved)}${sum(approved)?` — ${sum(approved)} before fees/tax`:''}.`,refs(approved),75);
  const largest=rows.filter(i=>i.total>0&&i.status!=='declined').sort((a,b)=>b.total-a.total)[0];
  const duplicateLargest=largest && (pending.includes(largest)||extra.includes(largest)||(approved.length===1&&approved[0]===largest&&(proposed.length||pending.length||extra.length)));
  if(largest && !duplicateLargest)add(`Largest line: ${short(largest.title)} at ${money(largest.total)}.`,refs([largest]),70);
  const laborOnly=rows.every(i=>i.parts===0 && i.labor!=null && i.total===i.labor && !i.other);
  if(laborOnly && rows.some(i=>i.total>0))add(`${sum(rows)} in listed work is labor; no parts charge is recorded.`,refs(rows),71);
  if(d.fees!=null && d.tax!=null && d.fees+d.tax>0)add(`${money(d.fees+d.tax)} of the total is fees and tax${d.fees>0?` (${money(d.fees)} fees)` : ''}.`,['DT'],60);
  if(completed.length)add(`Completed: ${names(completed)}.`,refs(completed),55);
  if(proposed.length)add(`Proposed, not recorded as approved: ${names(proposed)}.`,refs(proposed),56);
  if(d.total===0)add('The document lists a $0 total for this visit. Keep it as a service-history record.',['DT'],90);
  const keyPoints=candidates.sort((a,b)=>b.priority-a.priority).slice(0,3).map((c,i)=>({id:`K${i+1}`,text:c.text,provenance:c.provenance,quoteIds:c.quoteIds}));
  const workLabel=service?'Work recorded':invoice?'Invoice covers':'Work proposed';
  const genericQuestion=extra.length?'What is the extra scope and amount before I approve it?':pending.length?`What test result determines ${short(pending[0].title).toLowerCase()}?`:declined.length?'Can you separate the declined items from the completed or approved work?':completed.length===rows.length?'What results and repair warranties can I keep with this record?':`What findings support ${short(rows[0].title).toLowerCase()}?`;
  const headline=narrative?narrative[service?3:0]:`${service||invoice?'This visit covers':'This proposal covers'} ${short(rows[0].title).toLowerCase()}${rows.length>1?' and related work':''}.`;
  const estimateRequest=narrative?narrative[service?4:1]:`${names(completed.length?completed:rows)}${completed.length?' is recorded as completed.':'; check the approval status of each line.'}`;
  const simpleNextStep=narrative?narrative[service?5:2]:genericQuestion;
  const totalLine=`${money(d.total)} ${service||invoice?'recorded':'quoted'} total.${reconciliation.incomplete?' Some amounts are not stated.':reconciliation.needsReview?' The line totals do not match.':''}`;
  return {headline,estimateRequest,simpleNextStep,totalLine,keyPoints,sourceLabel,workLabel,curated:Boolean(narrative)};
}
