import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3011/#/my');
 await page.waitForFunction(()=>document.querySelectorAll('.library-row').length===3);
 assert.equal(await page.locator('#mode-banner').isVisible(),false);
 await page.screenshot({path:'artifacts/my-page-desktop.png',fullPage:true});
 await page.locator('#library-filter').selectOption('Receipt');
 assert.equal(await page.locator('.library-row').count(),1);
 await page.getByRole('button',{name:'Open',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.library-preview canvas')?.width>0);
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('#library-add').click();
 await page.locator('#library-file').setInputFiles({name:'receipt-photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jP1sAAAAASUVORK5CYII=','base64')});
 await page.getByText('Document saved to your library.').waitFor();
 await page.reload();
 await page.waitForFunction(()=>document.querySelectorAll('.library-row').length===4);
 await page.locator('#library-search').fill('receipt-photo');
 assert.equal(await page.locator('.library-row').count(),1);
 await page.getByRole('button',{name:'Open',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.library-original-image')?.naturalWidth>0);
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Remove receipt-photo.png'}).click();
 await page.getByText('Document removed from this library.').waitFor();
 await page.getByRole('link',{name:'Edit profile'}).click();
 await page.locator('[name=name]').fill('Jordan');
 await page.locator('[name=mileage]').fill('42000');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.locator('[name=insurance]').selectOption('');
 await page.getByRole('button',{name:'Save my profile'}).click();
 await page.getByRole('heading',{name:'Jordan’s garage'}).waitFor();
 assert.match(await page.locator('.insurance-card').innerText(),/Add insurance/);
 assert.match(await page.locator('.warranty-card').innerText(),/18,000 mi/);
 await page.reload();
 await page.getByRole('heading',{name:'Jordan’s garage'}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.waitForFunction(()=>document.querySelectorAll('.library-row').length===3);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'My page overflow');
 assert.equal(await page.getByRole('link',{name:'My page',exact:true}).isVisible(),true);
 await page.screenshot({path:'artifacts/my-page-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('My page passed: sample PDFs, search/filter, upload and refresh, photo preview, removal, onboarding/profile persistence, mobile navigation and layout.');
} finally {await browser.close();}
