import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  await context.route('https://fonts.googleapis.com/**', route => route.abort());
  await context.route('https://fonts.gstatic.com/**', route => route.abort());
  const page = await context.newPage();
  page.on('pageerror', error => { errors.push(error.message); console.error('Browser error:', error.message); });
  const origin = process.env.CARRA_TEST_URL || 'http://localhost:3011';
  await page.goto(origin);
  assert.equal(await page.locator('#mode-banner').isVisible(), false);
  await page.getByRole('heading', { name: 'Car ownership, with a copilot.' }).waitFor();
  await page.screenshot({ path: 'artifacts/landing-desktop.png', fullPage: true });
  await page.getByRole('tab', { name: 'Maintenance & records' }).click();
  assert.match(await page.locator('#carra-preview').innerText(), /Your garage is ready/);
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab', { name: 'Everyday car questions' }).getAttribute('aria-selected'), 'true');
  assert.match(await page.locator('#carra-preview').innerText(), /General car chat is coming next/);
  await page.getByRole('tab', { name: 'Repair estimates' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'artifacts/landing-mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Landing: horizontal overflow');
  await page.getByRole('button', { name: 'Take a look around' }).click();
  assert.equal(await page.locator('#explore-title').evaluate(el => el === document.activeElement), true);
  await page.getByText('Can I try it without uploading anything?', { exact: true }).click();
  await page.getByRole('button', { name: 'Open a sample estimate' }).waitFor({ state: 'visible' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'New estimate', exact: true }).click();
  assert.equal(await page.locator('#mode-banner').isVisible(), true);
  await page.getByRole('link', { name: 'Home', exact: true }).click();
  assert.deepEqual(errors, [], 'No errors during initial render');
  await page.getByRole('link', { name: 'Try Carra', exact: true }).click();
  await page.screenshot({ path: 'artifacts/input-desktop.png', fullPage: true });
  for (const sample of ['ev6-12v', 'crv-brake', 'a4-idle']) {
    await page.goto(`${origin}/#/analyze/new`);
    await page.locator('#document-sample').selectOption({ 'ev6-12v': 'estimate-29', 'crv-brake': 'estimate-01', 'a4-idle': 'estimate-18' }[sample]);
    await page.getByRole('button', { name: 'Read document', exact: true }).click();
    await page.waitForURL(/\/review$/);
    assert.match(await page.locator('#reconciliation').innerText(), /Totals match/);
    if (sample === 'ev6-12v') {
      await page.locator('[name=grandTotal]').fill('601.36');
      assert.match(await page.locator('#reconciliation').innerText(), /don't match/);
      await page.reload();
      assert.equal(await page.locator('[name=grandTotal]').inputValue(), '601.36');
      await page.locator('[name=grandTotal]').fill('600.36');
      await page.locator('.edit-item').first().locator('[name=status]').selectOption('declined');
      await page.screenshot({ path: 'artifacts/review-desktop.png', fullPage: true });
    }
    await page.getByRole('button', { name: 'Looks right, explain it' }).click();
    await page.waitForURL(url => /\/analyze\/estimate-[a-z0-9-]+$/.test(url.hash));
    await page.locator('#vehicle-name').waitFor({ state: 'visible' });
    assert.equal(await page.locator('.item-row').count(), 3);
    assert.equal(await page.locator('#question-list > li').count(), 3);
    assert.equal(await page.locator('#key-points .quote-card').count(), 0);
    await page.locator('#key-points .quote-chip:visible').first().click();
    assert.ok(await page.locator('#key-points .quote-card').count() >= 1);
    await page.locator('#key-points .quote-chip:visible').first().click();
    await page.locator('.item-row').first().click();
    await page.locator('#detail-0 .item-evidence summary').click();
    assert.match(await page.locator('#detail-0').innerText(), /Public records were not checked/);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#row-0').evaluate(el => el === document.activeElement), true);
    await page.locator('#suggestions button').first().click();
    await page.locator('.assistant-message').waitFor();
    assert.equal(await page.locator('.assistant-message').count(), 1);
    await page.getByRole('button', { name: 'How we checked' }).click();
    assert.match(await page.locator('#checked-body').innerText(), /Not checked/);
    await page.getByRole('button', { name: 'View technical trace' }).click();
    assert.equal(await page.locator('#trace-list li').count(), 6);
    await page.reload();
    await page.locator('#vehicle-name').waitFor({ state: 'visible' });
    if (sample === 'ev6-12v') {
      assert.match(await page.locator('#row-0').innerText(), /Declined/);
      await page.screenshot({ path: 'artifacts/report-desktop.png', fullPage: true });
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: `artifacts/${sample}-mobile.png`, fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `${sample}: horizontal overflow`);
    const glance = await page.locator('#glance').boundingBox();
    console.log(`${sample}: mobile glance bottom ${Math.round(glance.y + glance.height)}px`);
    assert.ok(glance.y + glance.height <= 844, `${sample}: glance exceeds first viewport`);
    await page.locator('.item-row').first().click();
    await page.locator('#item-sheet').waitFor({ state: 'visible' });
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#row-0').evaluate(el => el === document.activeElement), true);
    await page.setViewportSize({ width: 1440, height: 1000 });
  }
  await page.goto(`${origin}/#/analyze/new`);
  await page.getByRole('button', { name: 'Use my estimate' }).click();
  await page.locator('#document-files').setInputFiles('design/carra-character/carra-agent.png');
  await page.locator('.document-file').waitFor();
  await page.getByRole('button', { name: 'Enter details manually' }).click();
  await page.waitForURL(/\/review$/);
  await page.locator('#review-reference img').waitFor();
  await page.locator('[name=vehicle]').fill('2020 Example Vehicle');
  await page.locator('[name=shop]').fill('Test Shop');
  await page.locator('[name=title]').fill('Brake inspection');
  await page.locator('[name=source_text]').fill('<img src=x onerror=alert(1)> Inspect brakes.');
  await page.locator('[name=labor]').fill('50');
  await page.locator('[name=total]').fill('50');
  await page.locator('[name=grandTotal]').fill('50');
  await page.reload();
  await page.locator('#review-reference img').waitFor();
  await page.getByRole('button', { name: 'Looks right, explain it' }).click();
  await page.waitForURL(url => /\/analyze\/estimate-[a-z0-9-]+$/.test(url.hash));
  await page.locator('.item-row').first().click();
  await page.locator('#detail-0 .item-evidence summary').click();
  assert.match(await page.locator('#detail-0').innerText(), /<img src=x onerror=alert\(1\)>/);
  assert.equal(await page.locator('#detail-0 .quote-card img').count(), 0);
  await page.getByRole('link', { name: 'Home', exact: true }).click();
  assert.equal(await page.locator('.history-list li').count(), 4);
  await page.getByRole('button', { name: 'Give Carra a try' }).click();
  await page.waitForURL(/\/review$/);
  assert.match(await page.locator('[name=vehicle]').inputValue(), /Kia EV6/);
  await page.goto(`${origin}/#/analyze/missing`);
  await page.getByRole('heading', { name: 'Estimate not found' }).waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: three samples, edits, persistence, quotes, trace, mobile sheets, manual uploads, HTML escaping, and missing routes.');
} finally { await browser.close(); }
