import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'no-preference' });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://localhost:3011');
  await page.waitForFunction(() => document.querySelector('.hero-mascot video')?.currentTime > .2);
  await page.getByRole('button', { name: 'Pause Carra animation' }).click();
  assert.equal(await page.locator('.hero-mascot video').evaluate(v => v.paused), true);
  await page.screenshot({ path: 'artifacts/landing-animated-desktop.png', fullPage: false });
  await page.getByRole('button', { name: 'Play Carra animation' }).click();
  await page.waitForFunction(() => document.querySelector('.hero-mascot video')?.ended);
  assert.equal(await page.locator('.hero-mascot video').evaluate(v => v.loop), false);
  await page.getByRole('button', { name: 'Replay Carra greeting' }).click();
  await page.waitForFunction(() => !document.querySelector('.hero-mascot video').paused);
  await page.getByRole('button', { name: 'Take a look around' }).click();
  await page.waitForFunction(() => document.querySelector('.hero-mascot video').paused);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.reload();
  assert.equal(await page.locator('.hero-mascot video').getAttribute('src'), null);
  assert.equal(await page.locator('.hero-mascot').evaluate(el => el.classList.contains('is-playing')), false);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.hero-mascot').scrollIntoViewIfNeeded();
  await page.getByRole('button', { name: 'Play Carra greeting' }).click();
  await page.waitForFunction(() => document.querySelector('.hero-mascot video').currentTime > .2);
  await page.getByRole('button', { name: 'Pause Carra animation' }).click();
  await page.screenshot({ path: 'artifacts/landing-animated-mobile.png', fullPage: false });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('link', { name: 'New estimate', exact: true }).click();
  assert.equal(await page.locator('.hero-mascot video').count(), 0);
  await page.route('**/waiting.mp4', route => route.abort());
  await page.getByRole('link', { name: 'Home', exact: true }).click();
  await page.locator('.hero-mascot').scrollIntoViewIfNeeded();
  await page.getByRole('button', { name: 'Play Carra greeting' }).click();
  await page.getByRole('button', { name: 'Carra greeting unavailable' }).waitFor();
  assert.equal(await page.locator('.mascot-motion-control').isDisabled(), true);
  assert.equal(await page.locator('.hero-mascot').evaluate(el => el.classList.contains('is-playing')), false);
  assert.deepEqual(errors, []);
  console.log('Motion checks passed: playback, pause, replay, offscreen pause, reduced motion, mobile, route cleanup, and failed-video fallback.');
} finally { await browser.close(); }
